Lecture04
NakanoYm/Raisetech pull request #5
Opened 2024-02-22 13:21 UTC by NakanoYm

課題４を提出致します。
ご確認よろしくお願い致します。

2024-02-22 14:14 UTC, MasatoshiMizumoto requested changes
EC2とRDSですが、ご自身が作成したVPC上に構築したという証跡ではないので、
スクショの撮り直しをお願いします！！

2024-02-23 02:32 UTC, NakanoYm commented
ご確認ありがとうございます。
画像を変更しましたので、ご確認よろしくお願い致します。

2024-02-23 03:08 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-02-23 03:08 UTC, MasatoshiMizumoto commented on img04/RDS-2.png
これは求めていたものと異なる（VPC-IDはあるが、そもそも課題で作ったVPCのIDではない）ので、再調査お願いします！！

2024-02-23 05:42 UTC, NakanoYm commented
課題用に作成したVPC上に構築されたEC2とRDSがわかるように画像を修正しました。
ご確認よろしくお願い致します。

2024-02-23 05:44 UTC, MasatoshiMizumoto approved these changes
LGTMです！
お疲れさまでした！

2024-02-23 08:18 UTC, merged